/* Tournament of Albums — runtime configuration.

   Local-dev default. Deployed environments get this file GENERATED by
   Terraform (toa-terraform/modules/toa-web/main.tf) — editing this file
   does not change any deployed site.

   Loaded as a blocking script from the <head> of index.html and viz.html,
   so it must have run before the inline page scripts read it. */
window.TOA_CONFIG = {
  apiBaseUrl: "https://toa-api.tor-gu.com",
  environment: "local",
};
